# Generated by Django 5.0.3 on 2024-06-16 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email',
            new_name='sub_email',
        ),
    ]
